### ISSUE TITLE
Fonts folder empty

### ISSUE THREAD

**Issue by joostmaes** [bigxixi/Font-Packer#2]
Fonts folder is empty. Plugin does not seem to work.

**Comment by bigxixi** [comment]
Please tell me your sketch version, and your system language.
Send me a copy of the sketch file you found it not work if possible.
my email: xixi@bigxixi.com

**Comment by bstefan** [comment]
Same here, Version 40.3 (33839)

**Comment by bigxixi** [comment]
@joostmaes @bstefan Are you on macOS Sierra (MacOS 10.12)?
There are some changes if you update to Sierra about some font file paths, which may effect this script, but I need more information. Can you help check if this direction exist on your system please?"/System/Library/Assets/com_apple_MobileAsset_Font3/"
Thank you for your feedbacks!

**Comment by bstefan** [comment]
@bigxixi I can't find it.

**Comment by bigxixi** [comment]
@joostmaes @bstefan try this :
https://github.com/bigxixi/ReadMe-Resources/raw/master/Font-Packer/Font-PackerTest.sketchplugin.zip
and let me know if your problems solved :)

**Comment by bstefan** [comment]
It works. Thanks!

**Comment by bigxixi** [comment]
@bstefan you are welcome! Thank you for helping improve the plugin!
